#Requires -Version 5.1
<#
.SYNOPSIS
    [AgentName] Audit Script - [Domain Description]

.DESCRIPTION
    Automated audit script for the [AgentName] agent.
    Checks [domain] for compliance with agent standards.

    Part of the AI Agent Agency framework.

.EXAMPLE
    .\scripts\audit-template.ps1

.EXAMPLE
    .\scripts\audit-template.ps1 -Verbose
#>

[CmdletBinding()]
param()

# Load shared audit utilities
. "$PSScriptRoot\_audit-common.ps1"

# ============================================================================
# CONFIGURATION - Customize these for your agent
# ============================================================================

$AgentName = "YourAgent"
$AgentEmoji = "🔍"
$AgentRole = "Your Agent Role"
$AuditTitle = "Domain Audit Report"

# Paths to scan (relative to project root)
$ScanPaths = @(
    (Join-Path $ProjectRoot "src")
    # Add more paths as needed
)

# Output report path
$ReportPath = Join-Path $AuditsDir "AUDIT_your-domain.md"
$ScriptRelPath = "scripts/audit-your-domain.ps1"

# ============================================================================
# COUNTERS
# ============================================================================

$totalChecks = 0
$passed = 0
$warnings = 0
$failed = 0
$results = @()

# ============================================================================
# AUDIT CHECKS - Add your checks here
# ============================================================================

Write-AuditHeader -AgentName $AgentName -AgentEmoji $AgentEmoji -AuditTitle $AuditTitle

# --- Check 1: Example file scan ---
Write-Host "  Scanning files..." -ForegroundColor DarkGray

$files = Get-SourceFiles -Path $ScanPaths[0] -Include @("*.css", "*.js")
foreach ($file in $files) {
    $totalChecks++
    $relativePath = $file.FullName.Replace($ProjectRoot, "").TrimStart("\")

    # Example: check for hardcoded colors
    $issues = Search-FileContent -FilePath $file.FullName -Pattern '#[0-9A-Fa-f]{6}'

    if ($issues) {
        $warnings++
        Write-CheckResult -Item $relativePath -Status "WARN" -Message "$($issues.Count) hardcoded colors found"
        $results += [PSCustomObject]@{
            File = $relativePath
            Status = "WARN"
            Issues = "$($issues.Count) hardcoded colors"
        }
    } else {
        $passed++
        Write-CheckResult -Item $relativePath -Status "PASS"
        $results += [PSCustomObject]@{
            File = $relativePath
            Status = "PASS"
            Issues = "-"
        }
    }
}

# --- Check 2: Add more checks as needed ---
# $totalChecks++
# if (condition) { $passed++ } else { $warnings++ }

# ============================================================================
# GENERATE REPORT
# ============================================================================

$reportContent = New-AuditReport -AgentName $AgentName -AgentRole $AgentRole -ScriptPath $ScriptRelPath -OutputPath $ReportPath

$reportContent += @"

## Summary

| Metric | Count |
|--------|-------|
| Total Checks | $totalChecks |
| **Passed** | $passed |
| **Warnings** | $warnings |
| **Failed** | $failed |
| **Compliance** | $([math]::Round(($passed / [math]::Max($totalChecks, 1)) * 100))% |

---

## Results

| File | Status | Issues |
|------|--------|--------|
"@

foreach ($r in $results) {
    $statusIcon = switch ($r.Status) {
        "PASS" { ":white_check_mark: PASS" }
        "WARN" { ":warning: WARN" }
        "FAIL" { ":x: FAIL" }
    }
    $reportContent += "| ``$($r.File)`` | $statusIcon | $($r.Issues) |`n"
}

$reportContent += @"

## $AgentName Recommendations

After reviewing this audit, consider:
1. Fix any FAIL items immediately
2. Address WARN items in the next sprint
3. Review INFO items for best practices

---

*Report generated by $AgentName - $AgentRole Agent*
"@

# Save report
Save-AuditReport -Content $reportContent -OutputPath $ReportPath -AppendHistory

# ============================================================================
# SUMMARY
# ============================================================================

Write-AuditFooter -Passed $passed -Warnings $warnings -Failed $failed -Total $totalChecks
